/*
* generated by Xtext
*/
package br.ufc.great.catchml;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CatchMLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return br.ufc.great.catchml.ui.internal.CatchMLActivator.getInstance().getInjector("br.ufc.great.catchml.CatchML");
	}
	
}
