/*
* generated by Xtext
*/
package org.xtext.example.mydsl.ui.outline;
/*
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.xtext.example.mydsl.myDsl.HandlerDeclaration;
import org.xtext.example.mydsl.myDsl.LogicExpression;

/**
 * customization of the default outline structure
 * 
 *
public class CopyOfMyDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	protected boolean _isLeaf(LogicExpression exp) {
		return true;
	}
	
	protected boolean _isLeaf(HandlerDeclaration exp) {
		return true;
	}
}
*/