/*
* generated by Xtext
*/
package br.ufc.great.catchml.ui.contentassist;

import br.ufc.great.catchml.ui.contentassist.AbstractCatchMLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CatchMLProposalProvider extends AbstractCatchMLProposalProvider {

}
