/*
* generated by Xtext
*/
package org.xtext.example.mydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {
	
	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser createParser() {
		org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser result = new org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAbstractElementAccess().getAlternatives(), "rule__AbstractElement__Alternatives");
					put(grammarAccess.getDeclarationAccess().getAlternatives(), "rule__Declaration__Alternatives");
					put(grammarAccess.getPropositionTypeAccess().getAlternatives(), "rule__PropositionType__Alternatives");
					put(grammarAccess.getAbstractDeclarationAccess().getAlternatives(), "rule__AbstractDeclaration__Alternatives");
					put(grammarAccess.getPropagationDeclarationAccess().getAlternatives(), "rule__PropagationDeclaration__Alternatives");
					put(grammarAccess.getRelationalExpressionAccess().getOpAlternatives_1_1_0(), "rule__RelationalExpression__OpAlternatives_1_1_0");
					put(grammarAccess.getAdditiveExpressionAccess().getAlternatives(), "rule__AdditiveExpression__Alternatives");
					put(grammarAccess.getPrimaryExpressionAccess().getAlternatives(), "rule__PrimaryExpression__Alternatives");
					put(grammarAccess.getTemporalRelationalExpressionAccess().getOpAlternatives_1_1_0(), "rule__TemporalRelationalExpression__OpAlternatives_1_1_0");
					put(grammarAccess.getTemporalAdditiveExpressionAccess().getAlternatives(), "rule__TemporalAdditiveExpression__Alternatives");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getAlternatives(), "rule__TemporalPrimaryExpression__Alternatives");
					put(grammarAccess.getBINARYOPERATORAccess().getAlternatives(), "rule__BINARYOPERATOR__Alternatives");
					put(grammarAccess.getTEMPORALOPERATORAccess().getAlternatives(), "rule__TEMPORALOPERATOR__Alternatives");
					put(grammarAccess.getTEMPUNTILOPERATORAccess().getAlternatives(), "rule__TEMPUNTILOPERATOR__Alternatives");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getSystemDeclarationAccess().getGroup(), "rule__SystemDeclaration__Group__0");
					put(grammarAccess.getPropositionListAccess().getGroup(), "rule__PropositionList__Group__0");
					put(grammarAccess.getPropositionListAccess().getGroup_2(), "rule__PropositionList__Group_2__0");
					put(grammarAccess.getPropositionSingleAccess().getGroup(), "rule__PropositionSingle__Group__0");
					put(grammarAccess.getSituationTypeAccess().getGroup(), "rule__SituationType__Group__0");
					put(grammarAccess.getSituationDeclarationAccess().getGroup(), "rule__SituationDeclaration__Group__0");
					put(grammarAccess.getSemanticConstraintTypeAccess().getGroup(), "rule__SemanticConstraintType__Group__0");
					put(grammarAccess.getSemanticConstraintDeclarationAccess().getGroup(), "rule__SemanticConstraintDeclaration__Group__0");
					put(grammarAccess.getTransitionConstraintTypeAccess().getGroup(), "rule__TransitionConstraintType__Group__0");
					put(grammarAccess.getTransitionConstraintDeclarationAccess().getGroup(), "rule__TransitionConstraintDeclaration__Group__0");
					put(grammarAccess.getExceptionTypeAccess().getGroup(), "rule__ExceptionType__Group__0");
					put(grammarAccess.getExceptionDeclarationAccess().getGroup(), "rule__ExceptionDeclaration__Group__0");
					put(grammarAccess.getScopeTypeAccess().getGroup(), "rule__ScopeType__Group__0");
					put(grammarAccess.getScopeDeclarationAccess().getGroup(), "rule__ScopeDeclaration__Group__0");
					put(grammarAccess.getHandlerDeclarationAccess().getGroup(), "rule__HandlerDeclaration__Group__0");
					put(grammarAccess.getActionDeclarationAccess().getGroup(), "rule__ActionDeclaration__Group__0");
					put(grammarAccess.getSignalDeclarationAccess().getGroup(), "rule__SignalDeclaration__Group__0");
					put(grammarAccess.getRaiseDeclarationAccess().getGroup(), "rule__RaiseDeclaration__Group__0");
					put(grammarAccess.getPropertyTypeAccess().getGroup(), "rule__PropertyType__Group__0");
					put(grammarAccess.getPropertyDeclarationAccess().getGroup(), "rule__PropertyDeclaration__Group__0");
					put(grammarAccess.getOrExpressionAccess().getGroup(), "rule__OrExpression__Group__0");
					put(grammarAccess.getOrExpressionAccess().getGroup_1(), "rule__OrExpression__Group_1__0");
					put(grammarAccess.getAndExpressionAccess().getGroup(), "rule__AndExpression__Group__0");
					put(grammarAccess.getAndExpressionAccess().getGroup_1(), "rule__AndExpression__Group_1__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup(), "rule__RelationalExpression__Group__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup_1(), "rule__RelationalExpression__Group_1__0");
					put(grammarAccess.getAdditiveExpressionAccess().getGroup_0(), "rule__AdditiveExpression__Group_0__0");
					put(grammarAccess.getPrimaryExpressionAccess().getGroup_0(), "rule__PrimaryExpression__Group_0__0");
					put(grammarAccess.getPrimaryExpressionAccess().getGroup_2(), "rule__PrimaryExpression__Group_2__0");
					put(grammarAccess.getPrimaryExpressionAccess().getGroup_3(), "rule__PrimaryExpression__Group_3__0");
					put(grammarAccess.getPrimaryExpressionAccess().getGroup_3_3(), "rule__PrimaryExpression__Group_3_3__0");
					put(grammarAccess.getTemporalOrExpressionAccess().getGroup(), "rule__TemporalOrExpression__Group__0");
					put(grammarAccess.getTemporalOrExpressionAccess().getGroup_1(), "rule__TemporalOrExpression__Group_1__0");
					put(grammarAccess.getTemporalAndExpressionAccess().getGroup(), "rule__TemporalAndExpression__Group__0");
					put(grammarAccess.getTemporalAndExpressionAccess().getGroup_1(), "rule__TemporalAndExpression__Group_1__0");
					put(grammarAccess.getTemporalRelationalExpressionAccess().getGroup(), "rule__TemporalRelationalExpression__Group__0");
					put(grammarAccess.getTemporalRelationalExpressionAccess().getGroup_1(), "rule__TemporalRelationalExpression__Group_1__0");
					put(grammarAccess.getTemporalAdditiveExpressionAccess().getGroup_0(), "rule__TemporalAdditiveExpression__Group_0__0");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getGroup_0(), "rule__TemporalPrimaryExpression__Group_0__0");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getGroup_2(), "rule__TemporalPrimaryExpression__Group_2__0");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getGroup_3(), "rule__TemporalPrimaryExpression__Group_3__0");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getGroup_4(), "rule__TemporalPrimaryExpression__Group_4__0");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getGroup_5(), "rule__TemporalPrimaryExpression__Group_5__0");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getGroup_5_3(), "rule__TemporalPrimaryExpression__Group_5_3__0");
					put(grammarAccess.getDomainmodelAccess().getElementsAssignment(), "rule__Domainmodel__ElementsAssignment");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
					put(grammarAccess.getSystemDeclarationAccess().getNameAssignment_1(), "rule__SystemDeclaration__NameAssignment_1");
					put(grammarAccess.getSystemDeclarationAccess().getDeclarationsAssignment_3(), "rule__SystemDeclaration__DeclarationsAssignment_3");
					put(grammarAccess.getPropositionListAccess().getHeadAssignment_1(), "rule__PropositionList__HeadAssignment_1");
					put(grammarAccess.getPropositionListAccess().getTailAssignment_2_1(), "rule__PropositionList__TailAssignment_2_1");
					put(grammarAccess.getPropositionSingleAccess().getValueAssignment_1(), "rule__PropositionSingle__ValueAssignment_1");
					put(grammarAccess.getPropositionDeclarationAccess().getNameAssignment(), "rule__PropositionDeclaration__NameAssignment");
					put(grammarAccess.getSituationTypeAccess().getValueAssignment_1(), "rule__SituationType__ValueAssignment_1");
					put(grammarAccess.getSituationDeclarationAccess().getNameAssignment_0(), "rule__SituationDeclaration__NameAssignment_0");
					put(grammarAccess.getSituationDeclarationAccess().getExpressionAssignment_2(), "rule__SituationDeclaration__ExpressionAssignment_2");
					put(grammarAccess.getSemanticConstraintTypeAccess().getValueAssignment_1(), "rule__SemanticConstraintType__ValueAssignment_1");
					put(grammarAccess.getSemanticConstraintDeclarationAccess().getNameAssignment_0(), "rule__SemanticConstraintDeclaration__NameAssignment_0");
					put(grammarAccess.getSemanticConstraintDeclarationAccess().getExpressionAssignment_2(), "rule__SemanticConstraintDeclaration__ExpressionAssignment_2");
					put(grammarAccess.getTransitionConstraintTypeAccess().getLabelAssignment_0(), "rule__TransitionConstraintType__LabelAssignment_0");
					put(grammarAccess.getTransitionConstraintTypeAccess().getValueAssignment_1(), "rule__TransitionConstraintType__ValueAssignment_1");
					put(grammarAccess.getTransitionConstraintDeclarationAccess().getNameAssignment_0(), "rule__TransitionConstraintDeclaration__NameAssignment_0");
					put(grammarAccess.getTransitionConstraintDeclarationAccess().getLeftAssignment_3(), "rule__TransitionConstraintDeclaration__LeftAssignment_3");
					put(grammarAccess.getTransitionConstraintDeclarationAccess().getRightAssignment_5(), "rule__TransitionConstraintDeclaration__RightAssignment_5");
					put(grammarAccess.getExceptionTypeAccess().getLabelAssignment_0(), "rule__ExceptionType__LabelAssignment_0");
					put(grammarAccess.getExceptionTypeAccess().getValueAssignment_1(), "rule__ExceptionType__ValueAssignment_1");
					put(grammarAccess.getExceptionDeclarationAccess().getNameAssignment_0(), "rule__ExceptionDeclaration__NameAssignment_0");
					put(grammarAccess.getExceptionDeclarationAccess().getExpressionAssignment_2(), "rule__ExceptionDeclaration__ExpressionAssignment_2");
					put(grammarAccess.getScopeTypeAccess().getLabelAssignment_0(), "rule__ScopeType__LabelAssignment_0");
					put(grammarAccess.getScopeTypeAccess().getValueAssignment_1(), "rule__ScopeType__ValueAssignment_1");
					put(grammarAccess.getScopeDeclarationAccess().getNameAssignment_0(), "rule__ScopeDeclaration__NameAssignment_0");
					put(grammarAccess.getScopeDeclarationAccess().getExceptionAssignment_3(), "rule__ScopeDeclaration__ExceptionAssignment_3");
					put(grammarAccess.getScopeDeclarationAccess().getHandlersAssignment_6(), "rule__ScopeDeclaration__HandlersAssignment_6");
					put(grammarAccess.getHandlerDeclarationAccess().getExpressionAssignment_2(), "rule__HandlerDeclaration__ExpressionAssignment_2");
					put(grammarAccess.getHandlerDeclarationAccess().getActionsAssignment_6(), "rule__HandlerDeclaration__ActionsAssignment_6");
					put(grammarAccess.getHandlerDeclarationAccess().getPropagationAssignment_8(), "rule__HandlerDeclaration__PropagationAssignment_8");
					put(grammarAccess.getActionDeclarationAccess().getExpressionAssignment_1(), "rule__ActionDeclaration__ExpressionAssignment_1");
					put(grammarAccess.getSignalDeclarationAccess().getExceptionAssignment_2(), "rule__SignalDeclaration__ExceptionAssignment_2");
					put(grammarAccess.getSignalDeclarationAccess().getScopeAssignment_5(), "rule__SignalDeclaration__ScopeAssignment_5");
					put(grammarAccess.getRaiseDeclarationAccess().getExceptionAssignment_2(), "rule__RaiseDeclaration__ExceptionAssignment_2");
					put(grammarAccess.getPropertyTypeAccess().getLabelAssignment_0(), "rule__PropertyType__LabelAssignment_0");
					put(grammarAccess.getPropertyTypeAccess().getValueAssignment_1(), "rule__PropertyType__ValueAssignment_1");
					put(grammarAccess.getPropertyDeclarationAccess().getNameAssignment_0(), "rule__PropertyDeclaration__NameAssignment_0");
					put(grammarAccess.getPropertyDeclarationAccess().getExpressionAssignment_2(), "rule__PropertyDeclaration__ExpressionAssignment_2");
					put(grammarAccess.getOrExpressionAccess().getOpAssignment_1_1(), "rule__OrExpression__OpAssignment_1_1");
					put(grammarAccess.getOrExpressionAccess().getRightAssignment_1_2(), "rule__OrExpression__RightAssignment_1_2");
					put(grammarAccess.getAndExpressionAccess().getOpAssignment_1_1(), "rule__AndExpression__OpAssignment_1_1");
					put(grammarAccess.getAndExpressionAccess().getRightAssignment_1_2(), "rule__AndExpression__RightAssignment_1_2");
					put(grammarAccess.getRelationalExpressionAccess().getOpAssignment_1_1(), "rule__RelationalExpression__OpAssignment_1_1");
					put(grammarAccess.getRelationalExpressionAccess().getRightAssignment_1_2(), "rule__RelationalExpression__RightAssignment_1_2");
					put(grammarAccess.getAdditiveExpressionAccess().getOpAssignment_0_1(), "rule__AdditiveExpression__OpAssignment_0_1");
					put(grammarAccess.getAdditiveExpressionAccess().getExprAssignment_0_2(), "rule__AdditiveExpression__ExprAssignment_0_2");
					put(grammarAccess.getPrimaryExpressionAccess().getExprAssignment_0_1(), "rule__PrimaryExpression__ExprAssignment_0_1");
					put(grammarAccess.getPrimaryExpressionAccess().getValueAssignment_1(), "rule__PrimaryExpression__ValueAssignment_1");
					put(grammarAccess.getPrimaryExpressionAccess().getOpBinAssignment_2_0(), "rule__PrimaryExpression__OpBinAssignment_2_0");
					put(grammarAccess.getPrimaryExpressionAccess().getLeftAssignment_2_2(), "rule__PrimaryExpression__LeftAssignment_2_2");
					put(grammarAccess.getPrimaryExpressionAccess().getRightAssignment_2_4(), "rule__PrimaryExpression__RightAssignment_2_4");
					put(grammarAccess.getPrimaryExpressionAccess().getOpMulAssignment_3_0(), "rule__PrimaryExpression__OpMulAssignment_3_0");
					put(grammarAccess.getPrimaryExpressionAccess().getArgsAssignment_3_2(), "rule__PrimaryExpression__ArgsAssignment_3_2");
					put(grammarAccess.getPrimaryExpressionAccess().getArgsAssignment_3_3_1(), "rule__PrimaryExpression__ArgsAssignment_3_3_1");
					put(grammarAccess.getTemporalOrExpressionAccess().getOpAssignment_1_1(), "rule__TemporalOrExpression__OpAssignment_1_1");
					put(grammarAccess.getTemporalOrExpressionAccess().getRightAssignment_1_2(), "rule__TemporalOrExpression__RightAssignment_1_2");
					put(grammarAccess.getTemporalAndExpressionAccess().getOpAssignment_1_1(), "rule__TemporalAndExpression__OpAssignment_1_1");
					put(grammarAccess.getTemporalAndExpressionAccess().getRightAssignment_1_2(), "rule__TemporalAndExpression__RightAssignment_1_2");
					put(grammarAccess.getTemporalRelationalExpressionAccess().getOpAssignment_1_1(), "rule__TemporalRelationalExpression__OpAssignment_1_1");
					put(grammarAccess.getTemporalRelationalExpressionAccess().getRightAssignment_1_2(), "rule__TemporalRelationalExpression__RightAssignment_1_2");
					put(grammarAccess.getTemporalAdditiveExpressionAccess().getOpAssignment_0_1(), "rule__TemporalAdditiveExpression__OpAssignment_0_1");
					put(grammarAccess.getTemporalAdditiveExpressionAccess().getExprAssignment_0_2(), "rule__TemporalAdditiveExpression__ExprAssignment_0_2");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getExprAssignment_0_1(), "rule__TemporalPrimaryExpression__ExprAssignment_0_1");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getValueAssignment_1(), "rule__TemporalPrimaryExpression__ValueAssignment_1");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getOpTempAssignment_2_0(), "rule__TemporalPrimaryExpression__OpTempAssignment_2_0");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getTemporalAssignment_2_2(), "rule__TemporalPrimaryExpression__TemporalAssignment_2_2");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getOpTempUntilAssignment_3_0(), "rule__TemporalPrimaryExpression__OpTempUntilAssignment_3_0");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getLeftExpAssignment_3_2(), "rule__TemporalPrimaryExpression__LeftExpAssignment_3_2");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getRightExpAssignment_3_4(), "rule__TemporalPrimaryExpression__RightExpAssignment_3_4");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getOpBinAssignment_4_0(), "rule__TemporalPrimaryExpression__OpBinAssignment_4_0");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getLeftAssignment_4_2(), "rule__TemporalPrimaryExpression__LeftAssignment_4_2");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getRightAssignment_4_4(), "rule__TemporalPrimaryExpression__RightAssignment_4_4");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getOpMulAssignment_5_0(), "rule__TemporalPrimaryExpression__OpMulAssignment_5_0");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getArgsAssignment_5_2(), "rule__TemporalPrimaryExpression__ArgsAssignment_5_2");
					put(grammarAccess.getTemporalPrimaryExpressionAccess().getArgsAssignment_5_3_1(), "rule__TemporalPrimaryExpression__ArgsAssignment_5_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser typedParser = (org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser) parser;
			typedParser.entryRuleDomainmodel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
