/*
* generated by Xtext
*/
package br.ufc.great.catchml.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import br.ufc.great.catchml.services.CatchMLGrammarAccess;

public class CatchMLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CatchMLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected br.ufc.great.catchml.parser.antlr.internal.InternalCatchMLParser createParser(XtextTokenStream stream) {
		return new br.ufc.great.catchml.parser.antlr.internal.InternalCatchMLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}
	
	public CatchMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CatchMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
