/*
 * generated by Xtext
 */
package br.ufc.great.catchml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.resource.IResourceSetProvider;
import org.eclipse.xtext.ui.resource.SimpleResourceSetProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CatchMLUiModule extends br.ufc.great.catchml.ui.AbstractCatchMLUiModule {
	public CatchMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	/*@Override
	public Class<? extends IEObjectHover> bindIEObjectHover() {
		return 	MydslEObjectHover.class;
	}*/
	
	@Override public Class<? extends IResourceSetProvider> bindIResourceSetProvider() {
	    return SimpleResourceSetProvider.class;
	}
}
