/*
 * generated by Xtext
 */
package br.ufc.great.catchml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CatchMLRuntimeModule extends br.ufc.great.catchml.AbstractCatchMLRuntimeModule {

}
